# Generated by Django 5.2 on 2025-04-22 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'female'), ('other', 'Other')], default='other', max_length=10, verbose_name='Gender')),
                ('specialization', models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('pediatrician', 'Pediatrician'), ('psychiatrist', 'Psychiatrist'), ('orthopedic', 'Orthopedic'), ('ent', 'ENT (Ear, Nose, Throat)'), ('gynecologist', 'Gynecologist'), ('oncologist', 'Oncologist'), ('general', 'General Physician')], default='general', max_length=30, verbose_name='Specialization')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
