# Generated by Django 5.2 on 2025-04-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('mappings', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.AlterUniqueTogether(
            name='patientdoctormapping',
            unique_together={('patient_id', 'doctor_id')},
        ),
    ]
