# Generated by Django 5.2 on 2025-04-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('mappings', '0002_rename_doctor_patientdoctormapping_doctor_id_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.AlterUniqueTogether(
            name='patientdoctormapping',
            unique_together={('patient', 'doctor')},
        ),
    ]
